// app/layout.tsx ou outro arquivo de layout principal

import type { Metadata } from "next";
import { Sora } from "next/font/google"; // Importa a fonte do Google
import "./globals.css";

// Configura a fonte Sora
const sora = Sora({
  subsets: ["latin"], // Subconjuntos de caracteres que você deseja usar
  variable: "--font-sora", // Nome da variável CSS para essa fonte
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // Intervalo de peso
});

// Metadados da página, como título e descrição
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define o layout principal com a fonte Sora aplicada ao body
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${sora.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
